### ISSUE TITLE
It fails to load the logfile here, even with the logcache active.

### ISSUE THREAD

**Issue by fribse** [amelchio/logbook_cache#1]
I'm at HA 0.104.3
logbook cache 4
connected through nabu casa.

When I open the logbook it will rotate for ever, and then show not logfile entries.
How can I help you with information?

**Comment by amelchio** [comment]
Are you saying that it is broken with and without logcache enabled?

To get more information, try enabling the debug logs:
```yaml
logger:
  default: warning
  logs:
    custom_components.logbook_cache: debug
```

Restart, wait 5 minutes and open the logbook from a fresh browser tab.

See what is logged in `home-assistant.log`.
