### ISSUE TITLE
logbook doesn't honor exclusions anymore

### ISSUE THREAD

**Issue by nenonano** [amelchio/logbook_cache#2]
Hi there
I'm testing your integration and I'm pleased to see how fast is now logbook.

What I've noticed is that logbook shows all the entries, even ones I've excluded in logbook configuration

my configuration:

```
logger:
  default: warning
  logs:
    custom_components.logbook_cache: warning

# View all events in a logbook
logbook:
 include:
    entities:
      - automation.v_04_led_tv_on
      - automation.v_05_led_tv_off
 #     - automation.climate_on_night_weekend
 #     - automation.climate_on_night_workday
 #     - automation.climate_on_weekend
 #     - automation.climate_on_workday
 exclude:
    entities:
      - sensor.Owl
      - binary_sensor.finestra
      - binary_sensor.salotto
      - sensor.Time
      - sensor.kpLastHeartbeat 
      - sensor.kpMQTTFailedConnections
      - sensor.kpMQTTRestarts
      - sensor.kpMQTTConnectionStatus
      - sensor.kpConnectorStatus
      - sensor.kpLastHARestart 
      - sensor.kpSystemRestarts
      - sensor.kpHARestarts
      - sensor.kpHeartbeaterStatus
      - sensor.kpMissedHeartbeats
      - sensor.kpLastMqttRestart 
      - sensor.kpLastSystemRestart
      - binary_sensor.shelly
      - sensor.daylight
    domains:
      - sun
      - systemmonitor
      #- alarm
      - automation
      - weather
      - media_player
```

I see, in my logbook's page (just an example):

> 11:48  kpLastMqttRestart changed to 2019-12-30 13:21:32
> 11:48  kpMQTTFailedConnections changed to 941
> 11:48  kpMQTTRestarts changed to 305
> 11:48  kpMQTTConnectionStatus changed to Stable
> 11:48  kpConnectorStatus changed to Running
> 11:48  kpLastHARestart changed to 2020-01-22 22:06:33
> 11:48  kpSystemRestarts changed to 0
> 11:48  kpHARestarts changed to 42
> 11:48  kpMissedHeartbeats changed to 223

Home Assistant 0.104.3 running in docker on Ubuntu 18.04

am I missing anything?

TIA
